---

- name: Install beadm
  package:
    name: beadm
    state: present
  become: True

- name: Create new Boot Environment before deployment
  command: 'beadm create sysconf-{{ ansible_date_time.iso8601 }}'
  become: True

- name: Configure GOP
  template:
    src: 'base/loader.rc.local.j2'
    dest: '/boot/loader.rc.local'
    owner: 'root'
    group: 'wheel'
    mode: '0644'
  become: True

- name: Configure modules (loader.conf)
  copy:
    src: 'base/loader.conf'
    dest: '/boot/loader.conf'
    owner: 'root'
    group: 'wheel'
    mode: '0644'
  become: True

- name: Deploy rc.conf
  template:
    src: 'base/rc.conf.j2'
    dest: '/etc/rc.conf'
    owner: 'root'
    group: 'wheel'
    mode: '0644'
  become: True

- name: Deploy firewall rules
  template:
    src: 'base/ipfw.rules.j2'
    dest: '/etc/ipfw.rules'
    owner: 'root'
    group: 'wheel'
    mode: '0644'
  become: True

- name: Deploy sysctl.conf
  template:
    src: 'base/sysctl.conf.j2'
    dest: '/etc/sysctl.conf'
    owner: 'root'
    group: 'wheel'
    mode: '0644'
  become: True

- name: Deploy hosts file (from Dan Pollock)
  copy:
    src: 'base/someonewhocares'
    dest: '/etc/hosts'
    owner: 'root'
    group: 'wheel'
    mode: '0644'
  become: True

- name: Deploy resolv.conf and resolvconf.conf
  template:
    src: 'base/{{ item }}.j2'
    dest: '/etc/{{ item }}'
    owner: 'root'
    group: 'wheel'
    mode: '0644'
  with_items:
    - 'resolv.conf'
    - 'resolvconf.conf'
  become: True

# Ignore errors because there might be some connectivity problems when
# the role is executed.
- name: Install sudo
  package:
    name: 'sudo'
    state: present
  become: True
  ignore_errors: True

- name: Deploy sudo configuration
  template:
    src: 'base/sudoers.j2'
    dest: '{{ localetc }}/sudoers'
    owner: 'root'
    group: 'wheel'
    mode: '0440'
  become: True

- name: Remove extra sudo files
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '{{ localetc }}/sudoers.dist'
    - '{{ localetc }}/sudoers.d'
  become: True

- name: Deploy syslogd configuration
  template:
    src: 'base/syslog.conf.j2'
    dest: '/etc/syslog.conf'
    owner: 'root'
    group: 'wheel'
    mode: '0644'
  become: True

- name: Deploy crond configuration
  template:
    src: 'base/crontab.j2'
    dest: '/etc/crontab'
    owner: 'root'
    group: 'wheel'
    mode: '0644'
  become: True

- name: Deploy newsyslog configuration for cron
  template:
    src: 'base/newsyslog.conf.j2'
    dest: '/etc/newsyslog.conf'
    owner: 'root'
    group: 'wheel'
    mode: '0644'
  become: True

- name: Deploy periodic configuration overrides
  template:
    src: 'base/periodic.conf.j2'
    dest: '/etc/periodic.conf'
    owner: 'root'
    group: 'wheel'
    mode: '0644'
  become: True

- name: Add user to a specific groups
  user:
    name: {{ ansible_env.USER }}
    group: {{ ansible_env.USER }}
    groups: mpd,webcamd,wheel,operator
    append: True
  become: True

