#!/bin/sh
# ${1} - Name if the directory to package
# ${2} - Description

set -e

if test $# -ne 2; then
	(>&2 echo "There should be at least 2 arguments specified:")
	(>&2 echo "1 - The name of the directory to package")
	(>&2 echo "2 - The description for the package")
	exit 1
fi

if command -v dar; then
	DAR=dar
else
	(>&2 echo "DAR command not found in standard paths")
	exit 2
fi

COMPRESSION_RATIO=9
COMPRESSION_ALGO=xz
COMPRESSION=-z${COMPRESSION_ALGO}:${COMPRESSION_RATIO}
DATE=`date "+%Y-%m-%d"`
DAR_COMMENT_FORMAT="Archived by ${USER} at ${DATE}, UID: %u, GID: %g, ${COMPRESSION_ALGO}, level ${COMPRESSION_RATIO}"

# Invoke the predefined DAR command
# -c - Name of the DAR archive without extension
# -R - Directory to package

${DAR} \
	-c ${1} \
	-R ${1}/ \
	${COMPRESSION} \
	-. ${2} ${DAR_COMMENT_FORMAT} \
	-3 sha512

